services:
  - type: web
    name: ml-dashboard-backend
    env: python
    root: server
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: ml-dashboard-frontend
    env: node
    root: client
    buildCommand: npm ci && npm run build
    startCommand: npm run start
